// <auto-generated />
using AutomaticBackup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomaticBackup.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220209051643_2022020901")]
    partial class _2022020901
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("AutomaticBackup.IsAuto", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Auto")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("IsAuto");
                });

            modelBuilder.Entity("AutomaticBackup.USB", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("USB");
                });
#pragma warning restore 612, 618
        }
    }
}
